### PR TITLE
added support for sync writes through "/sync" option to "set" command

### PR DESCRIPTION
**Pull request by anight**
Hi,

Here is my patch, I hope it could be merged into master.

Thanks !

### CODE REVIEW

**Comment by erikfrey** [comment]
Hi @anight - thanks for submitting this patch.  It looks pretty good, but, can you describe your use case, specifically?  I'd like to understand why to support an optional sync flag per set, as opposed to:
- a `--sync` config option for the whole darner process
- a way to configure certain queues as always sync guaranteed
- occasionally running the `sync` unix command

**Comment by anight** [comment]
My workload consist of sequence of batches of 10000 records each which I'm pushing through darner. One of requirements I've got is a reliable store, that means, in case of connection loss or server downtime the process is restarted from the start of interrupted batch. So in order to keep good throughput the first 9999 records are stored asynchronously and the last one with "/sync", which also implicitly stores all previous unsaved data to disk. This scenario pretty well described here (section Synchronous Writes): http://leveldb.googlecode.com/svn/trunk/doc/index.html

**Comment by erikfrey** [comment]
Ok - please add a test to the parser, and then I will merge this.

**Comment by erikfrey** [comment]
Thanks @anight !

**Pull request merged**
